### ISSUE TITLE
k: raise AttributeError

### ISSUE THREAD

**Issue by msiddiqi** [twitter/cdk#26]
Trying to run it on windows and getting this error.

$ cdk sample.asc
  File "c:\python34\lib\site-packages\cdk\data\asciidoc-8.6.8/asciidoc.py", line 101
    except KeyError, k: raise AttributeError, k
                   ^
SyntaxError: invalid syntax
b''

**Comment by simeonf** [comment]
That's actually a Python 3.4 problem. The underlying library asciidoc is Python 2.x only. Try again on windows with 2.7?
